#!/usr/bin/env python3
"""
Stage 4+5: LaTeX 渲染 + PDF 编译（国产模型增强版）
==================================================
- 中文支持: ctexart + 宋体/黑体 (tectonic 自动下载宏包)
- 编译引擎: tectonic (单文件现代 LaTeX, 无需本机装 TeX Live)
- 题目 + 解答交替排版，boxed 最终答案
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path


# ═══════════════════════════════════════════════════════
# 模板
# ═══════════════════════════════════════════════════════

def _build_preamble(course: str, student: str, title: str, date_str: str) -> str:
    return f"""\\documentclass[11pt, a4paper]{{ctexart}}

\\usepackage{{amsmath, amssymb, amsthm}}
\\usepackage{{geometry}}
\\usepackage{{fancyhdr}}
\\usepackage{{enumitem}}
\\usepackage{{xcolor}}
\\usepackage{{hyperref}}
\\usepackage{{fontspec}}
\\setCJKmainfont{{Songti SC}}
\\setCJKsansfont{{PingFang SC}}
\\setCJKmonofont{{Songti SC}}

\\geometry{{margin=2.2cm}}
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\rhead{{{escape(course)}}}
\\lhead{{{escape(student)}}}
\\rfoot{{Page \\thepage}}

\\newcommand{{\\problem}}[1]{{\\subsection*{{Problem #1}}}}
\\newcommand{{\\solution}}{{\\par\\noindent\\textbf{{Solution.}}\\par\\smallskip}}
\\definecolor{{anscolor}}{{RGB}}{{0, 80, 160}}
\\definecolor{{badcolor}}{{RGB}}{{180, 0, 0}}

\\begin{{document}}

\\begin{{center}}
  {{\\LARGE {escape(title)}}}\\\\[0.4em]
  {{\\large {escape(course)}}}\\\\[0.25em]
  {escape(student)} \\quad | \\quad {escape(date_str)}
\\end{{center}}

\\hrule
\\vspace{{0.8em}}
"""


POSTAMBLE = "\n\\end{document}\n"


# ═══════════════════════════════════════════════════════
# 转义
# ═══════════════════════════════════════════════════════

def escape(text: str) -> str:
    special = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_",
               "~": r"\textasciitilde{}"}
    for ch, rep in special.items():
        text = text.replace(ch, rep)
    return text


def clean(text: str) -> str:
    parts = re.split(r"(\$\$.*?\$\$|\$.*?\$)", text, flags=re.DOTALL)
    out = []
    for p in parts:
        if p.startswith("$"):
            out.append(p)
        else:
            out.append(escape(p))
    return "".join(out)


# ═══════════════════════════════════════════════════════
# 渲染
# ═══════════════════════════════════════════════════════

def render_one(sol: dict) -> str:
    pid = sol["problem_id"]
    lines = [f"\\problem{{{pid}}}", "", clean(sol.get("problem_text", "")), ""]

    if sol.get("solved"):
        lines.append("\\solution")
        for step in sol.get("steps", []):
            lines.append(clean(step))
            lines.append("")
        ans = sol.get("answer_latex", "")
        if ans:
            lines.append(f"\\noindent{{\\bfseries Final Answer:}}")
            lines.append(f"\\[\\boxed{{\\textcolor{{anscolor}}{{{ans}}}}}\\]")
            lines.append("")
    else:
        reason = sol.get("reason", "未自动求解")
        lines.append(f"\\textit{{\\color{{badcolor}}\\footnotesize 未自动求解: {escape(reason)}}}")
        lines.append("")

    for sub in sol.get("sub_solutions", []):
        lines.append(render_sub(sub))

    lines.append("\\vspace{0.6em}\\hrule\\vspace{0.6em}")
    return "\n".join(lines)


def render_sub(sub: dict) -> str:
    sid = sub["problem_id"].split(".")[-1]
    out = [f"\\noindent\\textbf{{({sid})}}"]
    if sub.get("solved"):
        for step in sub.get("steps", []):
            out.append(clean(step))
        if sub.get("answer_latex"):
            out.append(f"$\\boxed{{{sub['answer_latex']}}}$")
    else:
        out.append(f"\\textit{{\\color{{badcolor}}\\footnotesize {escape(sub.get('reason','未求解'))}}}")
    out.append("")
    return "\n".join(out)


def render_document(solutions: list, course="Mathematics", student="Student",
                    title="Homework Solutions") -> str:
    preamble = _build_preamble(course, student, title, date.today().isoformat())
    body = "\n".join(render_one(s) for s in solutions)
    total = len(solutions)
    solved = sum(1 for s in solutions if s.get("solved"))
    body += (f"\n\\vspace{{1em}}\\noindent\\textit{{Auto-generated by "
             f"国产大模型作业流水线: {solved}/{total} solved.}}\n")
    return preamble + body + POSTAMBLE


# ═══════════════════════════════════════════════════════
# PDF 编译: 优先 tectonic, 回退 pdflatex/xelatex
# ═══════════════════════════════════════════════════════

def _find_tectonic() -> str | None:
    candidates = [
        os.path.expanduser("~/bin/tectonic"),
        shutil.which("tectonic"),
        "/usr/local/bin/tectonic",
        "/opt/homebrew/bin/tectonic",
    ]
    for c in candidates:
        if c and Path(c).exists() and os.access(c, os.X_OK):
            return c
    return None


def compile_pdf(tex_path: str, output_dir: str | None = None) -> bool:
    tex_path = Path(tex_path)
    output_dir = Path(output_dir) if output_dir else tex_path.parent

    tectonic = _find_tectonic()
    if tectonic:
        try:
            print(f"  使用 tectonic 编译: {tectonic}")
            r = subprocess.run(
                [tectonic, "--outdir", str(output_dir), str(tex_path)],
                capture_output=True, text=True, timeout=180,
            )
            if r.returncode == 0:
                pdf = output_dir / (tex_path.stem + ".pdf")
                if pdf.exists():
                    print(f"  ✅ PDF: {pdf}")
                    return True
            print(f"  ⚠️ tectonic stderr:\n{r.stderr[-800:]}")
        except Exception as e:
            print(f"  ⚠️ tectonic 失败: {e}")

    # 回退
    for engine in ["xelatex", "pdflatex"]:
        if shutil.which(engine):
            try:
                subprocess.run([engine, "-interaction=nonstopmode",
                                f"-output-directory={output_dir}", str(tex_path)],
                               capture_output=True, timeout=120)
                pdf = output_dir / (tex_path.stem + ".pdf")
                if pdf.exists():
                    return True
            except Exception:
                pass
    return False


# ═══════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════

def main():
    if len(sys.argv) < 3:
        print("用法: python render_latex.py <solutions.json> <output.tex> [--compile]")
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        solutions = json.load(f)
    doc = render_document(solutions)
    Path(sys.argv[2]).parent.mkdir(parents=True, exist_ok=True)
    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write(doc)
    print(f"[Stage 4] LaTeX: {sys.argv[2]}")
    if "--compile" in sys.argv:
        print("[Stage 5] PDF 编译")
        compile_pdf(sys.argv[2])


if __name__ == "__main__":
    main()
